# Generated by scripts/bootstrap-state.sh — safe to commit, contains no secrets.
# Credentials come from terraform/.s3-credentials via the environment.
bucket = "tfstate-solana-validator-k8s"
key    = "oci-testnet/terraform.tfstate"
region = "eu-frankfurt-1"

endpoints = {
  s3 = "https://frbfohzod0ut.compat.objectstorage.eu-frankfurt-1.oraclecloud.com"
}

use_path_style = true

# OCI is not AWS. Without these the backend tries to validate the region, call STS, and read the
# EC2 metadata service, all of which fail.
skip_region_validation      = true
skip_credentials_validation = true
skip_metadata_api_check     = true
skip_requesting_account_id  = true

# Required. OCI's S3 API rejects the newer AWS checksum headers, and the failure is an opaque
# 400 rather than anything that names checksums.
skip_s3_checksum = true
