{
 "title": "Solana Node",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "chain_name",
    "label": "Chain",
    "query": {
     "query": "label_values(solana_node_version,app)"
    }
   },
   {
    "name": "nodekey",
    "label": "Nodekey",
    "query": {
     "query": "label_values(solana_validator_delinquent,nodekey)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(solana_node_version,hostname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Fleet Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Solana Versions",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (app, version) (solana_node_version{app=\"$chain_name\"})",
     "legendFormat": "{{ app }} {{version}}"
    }
   ]
  },
  {
   "title": "Nodes Availability",
   "type": "stat",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(up{app=\"$chain_name\", job=\"solana-exporter\"}[$__range])",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Nodes Health",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_node_is_healthy{app=\"$chain_name\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Solana Client Versions",
   "type": "table",
   "description": "Solana client software version running on the node.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "solana_node_version{app=\"$chain_name\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Solana Behind",
   "type": "timeseries",
   "description": "Number of slots that the node is behind.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "solana_node_num_slots_behind{app=\"$chain_name\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  { "title": "Validator Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Validator Block Production Rate",
   "type": "timeseries",
   "description": "Rate at which the validator produces blocks (and skips slots) per minute.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "60 * sum by (nodekey, status) (rate(\n    solana_validator_leader_slots_by_epoch_total{app=\"$chain_name\", hostname=\"$host\", nodekey=\"$nodekey\"}[1h])\n)",
     "legendFormat": "{{nodekey}} / {{status}}"
    }
   ]
  },
  {
   "title": "Validator Block Size",
   "type": "timeseries",
   "description": "Total number of transactions per block.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "sum by (transaction_type) (solana_validator_block_size{app=\"$chain_name\", hostname=\"$host\", nodekey=\"$nodekey\"})",
     "legendFormat": "{{transaction_type}}"
    },
    {
     "expr": "sum(solana_validator_block_size{app=\"$chain_name\", hostname=\"$host\", nodekey=\"$nodekey\"})",
     "legendFormat": "total"
    },
    {
     "expr": "increase(solana_node_transactions_total{app=\"$chain_name\", hostname=\"$host\"}[5m]) / increase(solana_node_slot_height{app=\"$chain_name\", hostname=\"$host\"}[5m])",
     "legendFormat": "cluster average (5min)"
    }
   ]
  },
  {
   "title": "Validator Root Slot Slack Distance",
   "type": "timeseries",
   "description": "The distance from the configured nodekey's root slot to the maximum observed root slot.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Slots" } },
   "targets": [
    {
     "expr": "max(solana_validator_root_slot{app=\"$chain_name\", hostname=\"$host\"}) - sum(solana_validator_root_slot{app=\"$chain_name\", hostname=\"$host\", nodekey=\"$nodekey\"})",
     "legendFormat": "$nodekey"
    }
   ]
  },
  {
   "title": "Epoch Skip Rate",
   "type": "timeseries",
   "description": "Skip rate grouped by epoch, similar to validators.app",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * solana:cluster_epoch_skip_rate{hostname=\"$host\"}",
     "legendFormat": "cluster"
    },
    {
     "expr": "100 * solana:validator_epoch_skip_rate{hostname=\"$host\", nodekey=\"$nodekey\"}",
     "legendFormat": "{{nodekey}}"
    },
    {
     "expr": "100 * avg_over_time(solana:cluster_epoch_skip_rate{hostname=\"$host\"}[1d])",
     "legendFormat": "1d - cluster"
    },
    {
     "expr": "100 * avg_over_time(solana:validator_epoch_skip_rate{hostname=\"$host\", nodekey=\"$nodekey\"}[1d])",
     "legendFormat": "1d - {{nodekey}}"
    }
   ]
  },
  {
   "title": "Validator Vote Slack Distance",
   "type": "timeseries",
   "description": "The distance between the highest on-chain last vote slot, and the configured nodekey's last vote slot.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "max(solana_validator_last_vote{app=\"$chain_name\", hostname=\"$host\"}) - max(solana_validator_last_vote{app=\"$chain_name\", hostname=\"$host\", nodekey=\"$nodekey\"})",
     "legendFormat": "$nodekey"
    }
   ]
  },
  {
   "title": "Running Skip Rate",
   "type": "timeseries",
   "description": "Average skip rate over a running window.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * solana:cluster_hour_skip_rate{hostname=\"$host\"}",
     "legendFormat": "1h - cluster"
    },
    {
     "expr": "100 * solana:validator_hour_skip_rate{hostname=\"$host\", nodekey=\"$nodekey\"}",
     "legendFormat": "1h - $nodekey"
    },
    {
     "expr": "100 * solana:cluster_day_skip_rate{hostname=\"$host\"}",
     "legendFormat": "1d - cluster"
    },
    {
     "expr": "100 * solana:validator_day_skip_rate{hostname=\"$host\", nodekey=\"$nodekey\"}",
     "legendFormat": "1d - $nodekey"
    }
   ]
  },
  { "title": "Validator Rewards & Balances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Validator Active Stake",
   "type": "stat",
   "description": "Total validator stake, in SOL",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "k SOL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_validator_active_stake{app=\"$chain_name\", hostname=\"$host\", nodekey=\"$nodekey\"} / 1000",
     "legendFormat": "{{nodekey}}"
    }
   ]
  },
  {
   "title": "Current SOL Balances",
   "type": "stat",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "SOL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_account_balance{app=\"$chain_name\", hostname=\"$host\"}",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Active Stake Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "k SOL" } },
   "targets": [
    {
     "expr": "sum(solana_validator_active_stake{app=\"$chain_name\", hostname=\"$host\", nodekey=\"$nodekey\"}) / 1000",
     "legendFormat": "$nodekey"
    }
   ]
  },
  {
   "title": "Solana Account Balances",
   "type": "timeseries",
   "description": "Balance (in SOL) of monitored Solana addresses.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "SOL" } },
   "targets": [
    {
     "expr": "solana_account_balance{app=\"$chain_name\", hostname=\"$host\"}",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Fee Rewards",
   "type": "timeseries",
   "description": "Solana transaction fee rewards earned by tracked validators.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "SOL" } },
   "targets": [
    {
     "expr": "sum by (nodekey, epoch) (solana_validator_fee_rewards_total{app=\"$chain_name\", hostname=\"$host\"})",
     "legendFormat": "{{epoch}} / {{nodekey}}"
    }
   ]
  },
  {
   "title": "WIP: Lamports Per Transaction",
   "type": "timeseries",
   "description": "Hourly average amount of fee lamports earned per transaction.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "Lamports" } },
   "targets": [
    {
     "expr": "1e9 * \nsum by (nodekey) (increase(solana_validator_fee_rewards_total{app=\"$chain_name\", hostname=\"$host\"}[1h]))\n/\nsum by (nodekey) (sum_over_time(solana_validator_block_size{app=\"$chain_name\", hostname=\"$host\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Solana Fee Rewards",
   "type": "table",
   "description": "Solana transaction fee rewards (in SOL) earned in different epochs.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "sum by (epoch, nodekey) (solana_validator_fee_rewards_total{app=\"$chain_name\", hostname=\"$host\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Solana Inflation Rewards",
   "type": "table",
   "description": "Solana Inflation rewards (in SOL) for different epochs.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "targets": [
    {
     "expr": "sum by (epoch, votekey) (solana_validator_inflation_rewards_total{app=\"$chain_name\", hostname=\"$host\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cluster Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Current Epoch",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 79 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_node_epoch_number{app=\"$chain_name\", hostname=\"$host\"}",
     "legendFormat": "epoch"
    }
   ]
  },
  {
   "title": "Epoch Progress",
   "type": "stat",
   "description": "How far the cluster is through the current epoch.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (solana_node_slot_height{app=\"$chain_name\", hostname=\"$host\"} - solana_node_epoch_first_slot{app=\"$chain_name\", hostname=\"$host\"}) / \n(solana_node_epoch_last_slot{app=\"$chain_name\", hostname=\"$host\"} - solana_node_epoch_first_slot{app=\"$chain_name\", hostname=\"$host\"} + 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Validators: Active/Delinquent",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count (solana_validator_delinquent{app=\"$chain_name\", hostname=\"$host\"} == 1)",
     "legendFormat": "delinquent"
    },
    {
     "expr": "count (solana_validator_delinquent{app=\"$chain_name\", hostname=\"$host\"} == 0)",
     "legendFormat": "active"
    },
    {
     "expr": "count (solana_validator_delinquent{app=\"$chain_name\", hostname=\"$host\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Slot Time",
   "type": "timeseries",
   "description": "Average time between slots.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "1000 / (rate(solana_node_slot_height{app=\"$chain_name\"}[30m]) > 0)",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "Transactions/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(solana_node_transactions_total{app=\"$chain_name\", hostname=~\"$host\"}[$__rate_interval]) < 10000",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "Cluster Skip Rate",
   "type": "timeseries",
   "description": "Rolling cluster skip rate with different window lengths.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "targets": [
    {
     "expr": "100 * solana:cluster_hour_skip_rate",
     "legendFormat": "1-hour"
    },
    {
     "expr": "100 * solana:cluster_day_skip_rate",
     "legendFormat": "1-day"
    }
   ]
  }
 ]
}